# config.yaml — notify-only, runs every 5 min

interval: 5                # <-- lowercase!
username: "YOUR_BBDC_USERNAME"
password: "YOUR_BBDC_PASSWORD"

months: ["202508", "202509"]   # update monthly (YYYYMM)

sessions: [1,2,3,4,5,6,7,8]    # adjust to the sessions you want

enable_booking: false          # notify only, do NOT auto-book

captcha:
  login: false
  booking: false

telegram:
  enabled: true
  token: "YOUR_TELEGRAM_BOT_TOKEN"
  chat_id: "YOUR_TELEGRAM_CHAT_ID"

discord:
  enabled: false
  webhook: ""
